server:
  port: ${PORT:8080}
  error.whitelabel.enabled: false
  servlet:
    context-path: /banking/v1

---
mariaDB4j:
  port: 15881

spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari.idle-timeout: 10000
    url: jdbc:mysql://localhost:${mariaDB4j.port}/dev
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
  h2.console.enabled: true

logging:
  path: ./logs
  level:
    root: INFO
    org.tonycox.banking: DEBUG
debug: false
---
mariaDB4j:
  port: 15881

spring:
  profiles: test
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari.idle-timeout: 10000
    url: jdbc:mysql://localhost:${mariaDB4j.port}/test
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
    org.tonycox.banking: INFO